Fix annoying error.
I had been getting this error a bunch and it was making me crazy:

```
rails aborted!
NoMethodError: undefined method `last_comment' for
/Users/andy/projects/rails/giftery/Rakefile:6:in `<main>'
bin/rails:4:in `<main>'

Caused by:
Bootsnap::LoadPathCache::FallbackScan:
Bootsnap::LoadPathCache::FallbackScan
/Users/andy/projects/rails/giftery/Rakefile:6:in `<main>'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

Apparently it's related to rake 11, so I got rid of that.